# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtefactStagingDirectory)'
- task: AzureRMWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(41318ea6-1a92-4f63-9c98-46042db474c2)'
    appType: 'webAppLinux'
    WebAppName: 'carrent-gawe'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    
